steps:
# build the container images
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gke-react:$SHORT_SHA", "./app/"]
  # push the container image to gcloud registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gke-react:$SHORT_SHA"]

#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy","app/app.yaml"]
