steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm  
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm  
  args: ['test']
- name: "gcr.io/cloud-builders/npm"
  entrypoint: npm  
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/npm"
  entrypoint: npm  
  args: ["run", "serve"]
timeout: "1600s"













#steps:
# build the container images
#- name: "gcr.io/cloud-builders/docker"
#  args: ["build", "-t", "gcr.io/$PROJECT_ID/gke-react:$SHORT_SHA", "./app/"]
#  # push the container image to gcloud registry
#- name: "gcr.io/cloud-builders/docker"
#  args: ["push", "gcr.io/$PROJECT_ID/gke-react:$SHORT_SHA"]

#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy","app/app.yaml"]
